### ISSUE TITLE
relocate to Lightbend org on GitHub

### ISSUE THREAD

**Issue by SethTisue** [lightbend/ec2-start-stop#9]
@adriaanm I assume it's okay if just do this? I can take care of adding the usual boilerplate to the readme, and changing the license to Apache 2 while I'm at it

**Comment by adriaanm** [comment]
Thanks! Please do. There is one reference to this in scala-jenkins-infra. Would be good to update there

**Comment by SethTisue** [comment]
@ktoso can you use your typesafehub superpowers here? as usual, I forgot I don't have them. (but the good news is, I think there are very very few repos left to move.)

**Comment by ktoso** [comment]
ok moving

**Comment by SethTisue** [comment]
thanks Konrad!

@adriaanm scala-jenkins-infra update: scala/scala-jenkins-infra@bd8fd2c495c1148c758e3463676d42c6e7f4575f
